### ISSUE TITLE
Why are there //:pants-requirements.txt dependencies?

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/requirements-perf#1]
https://github.com/pantsbuild/requirements-perf/blob/278948ee931fb326285ef94864d547fe23d0358d/aa/ab/ac/ad/ae/af/BUILD#L9

**Comment by stuhood** [comment]
> So a pure-annoyance optimization, since we already fully parse the constraints file anyhow, is to used the parsed constraints to emit a normalized constraints file for the input to the process. This would eliminate whitespace / comment edits in the constraint file invalidating the resolve.

I see an opportunity/necessity to do this as part of https://github.com/pantsbuild/pants/issues/14053
